# Generated by Django 3.1 on 2020-08-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('student_number', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('graduation_year', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_joined', models.DateField(blank=True, default='', max_length=200, null=True)),
                ('last_login', models.DateTimeField(blank=True, default='', max_length=200, null=True)),
                ('degree', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('program', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cpm', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
