# Generated by Django 3.1 on 2020-08-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISworkshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cpm',
            new_name='CAPES_miles_points',
        ),
    ]
