# Generated by Django 3.1 on 2020-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISworkshop', '0002_auto_20200825_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static'),
        ),
    ]
